name: r_env
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-edger
  - bioconductor-sva
  - r-base=4.0.2
  - r-corrplot
  - r-data.table
  - r-dplyr
  - r-ggally
  - r-ggplot2
  - r-ggpubr
  - r-rcolorbrewer
  - r-seurat
  - r-viridis
